---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: democratic-csi-freenas-nfs
spec:
  interval: 30m
  chart:
    spec:
      chart: democratic-csi
      version: 0.14.6
      sourceRef:
        kind: HelmRepository
        name: democratic-csi
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    csiDriver:
      # should be globally unique for a given cluster
      name: "org.democratic-csi.nfs"

    storageClasses:
      - name: freenas-nfs-csi
        defaultClass: false
        reclaimPolicy: Delete
        volumeBindingMode: Immediate
        allowVolumeExpansion: true
        parameters:
          fsType: nfs

        mountOptions:
          - noatime
          - nfsvers=4
        secrets:
          provisioner-secret:
          controller-publish-secret:
          node-stage-secret:
          node-publish-secret:
          controller-expand-secret:

    driver:
      config:
        driver: freenas-nfs
        instance_id:
        httpConnection:
          protocol: http
          host: 192.168.1.246
          port: 80
          # use only 1 of apiKey or username/password
          # if both are present, apiKey is preferred
          # apiKey is only available starting in TrueNAS-12
          apiKey: ${TRUENAS_API_KEY}
          # username: root
          # password:
          allowInsecure: true
          # use apiVersion 2 for TrueNAS-12 and up (will work on 11.x in some scenarios as well)
          # leave unset for auto-detection
          #apiVersion: 2
        sshConnection:
          host: 192.168.1.246
          port: 22
          username: admin
          # use either password or key
          password: ${TRUENAS_PASSWORD}
          # privateKey: |
          #   ${TRUENAS_SSH_KEY}
        zfs:
          # can be used to override defaults if necessary
          # the example below is useful for TrueNAS 12
          cli:
            sudoEnabled: true
          #
          #  leave paths unset for auto-detection
          #  paths:
          #    zfs: /usr/local/sbin/zfs
          #    zpool: /usr/local/sbin/zpool
          #    sudo: /usr/local/bin/sudo
          #    chroot: /usr/sbin/chroot

          # can be used to set arbitrary values on the dataset/zvol
          # can use handlebars templates with the parameters from the storage class/CO
          #datasetProperties:
          #  "org.freenas:description": "{{ parameters.[csi.storage.k8s.io/pvc/namespace] }}/{{ parameters.[csi.storage.k8s.io/pvc/name] }}"
          #  "org.freenas:test": "{{ parameters.foo }}"
          #  "org.freenas:test2": "some value"

          datasetParentName: hdd/k8s/nfs/vols
          # do NOT make datasetParentName and detachedSnapshotsDatasetParentName overlap
          # they may be siblings, but neither should be nested in the other
          # do NOT comment this option out even if you don't plan to use snapshots, just leave it with dummy value
          detachedSnapshotsDatasetParentName: hdd/k8s/nfs/snaps
          datasetEnableQuotas: true
          datasetEnableReservation: false
          datasetPermissionsMode: "0777"
          datasetPermissionsUser: 0
          datasetPermissionsGroup: 0
          #datasetPermissionsAcls:
          #- "-m everyone@:full_set:allow"
          #- "-m u:kube:full_set:allow"

        nfs:
          #shareCommentTemplate: "{{ parameters.[csi.storage.k8s.io/pvc/namespace] }}-{{ parameters.[csi.storage.k8s.io/pvc/name] }}"
          shareHost: 192.168.1.246
          shareAlldirs: false
          shareAllowedHosts: []
          shareAllowedNetworks: []
          shareMaprootUser: root
          shareMaprootGroup: wheel
          shareMapallUser: ""
          shareMapallGroup: ""
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: democratic-csi-freenas-iscsi
spec:
  interval: 30m
  chart:
    spec:
      chart: democratic-csi
      version: 0.14.6
      sourceRef:
        kind: HelmRepository
        name: democratic-csi
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    csiDriver:
      # should be globally unique for a given cluster
      name: "org.democratic-csi.iscsi"

    # add note here about volume expansion requirements
    storageClasses:
      - name: freenas-iscsi-csi
        defaultClass: false
        reclaimPolicy: Delete
        volumeBindingMode: Immediate
        allowVolumeExpansion: true
        parameters:
          # for block-based storage can be ext3, ext4, xfs
          fsType: xfs

        mountOptions: []
        secrets:
          provisioner-secret:
          controller-publish-secret:
          node-stage-secret:
          node-publish-secret:
          controller-expand-secret:

    driver:
      config:
        driver: freenas-iscsi
        instance_id:
        node:
          hostPID: true
          driver:
            extraEnv:
              - name: ISCSIADM_HOST_STRATEGY
                value: nsenter
              - name: ISCSIADM_HOST_PATH
                value: /usr/local/sbin/iscsiadm
            iscsiDirHostPath: /usr/local/etc/iscsi
            iscsiDirHostPathType: ""
        httpConnection:
          protocol: http
          host: 192.168.1.246
          port: 80
          # use only 1 of apiKey or username/password
          # if both are present, apiKey is preferred
          # apiKey is only available starting in TrueNAS-12
          apiKey: ${TRUENAS_API_KEY}
          # username: root
          # password:
          allowInsecure: true
          # use apiVersion 2 for TrueNAS-12 and up (will work on 11.x in some scenarios as well)
          # leave unset for auto-detection
          #apiVersion: 2
        sshConnection:
          host: 192.168.1.246
          port: 22
          username: admin
          # use either password or key
          password: ${TRUENAS_PASSWORD}
          # privateKey: |
          #   ${TRUENAS_SSH_KEY}
        zfs:
          # can be used to override defaults if necessary
          # the example below is useful for TrueNAS 12
          cli:
            sudoEnabled: true
          #
          #  leave paths unset for auto-detection
          #  paths:
          #    zfs: /usr/local/sbin/zfs
          #    zpool: /usr/local/sbin/zpool
          #    sudo: /usr/local/bin/sudo
          #    chroot: /usr/sbin/chroot

          # can be used to set arbitrary values on the dataset/zvol
          # can use handlebars templates with the parameters from the storage class/CO
          #datasetProperties:
          #  "org.freenas:description": "{{ parameters.[csi.storage.k8s.io/pvc/namespace] }}/{{ parameters.[csi.storage.k8s.io/pvc/name] }}"
          #  "org.freenas:test": "{{ parameters.foo }}"
          #  "org.freenas:test2": "some value"

          datasetParentName: hdd/k8s/iscsi/v
          # do NOT make datasetParentName and detachedSnapshotsDatasetParentName overlap
          # they may be siblings, but neither should be nested in the other
          # do NOT comment this option out even if you don't plan to use snapshots, just leave it with dummy value
          detachedSnapshotsDatasetParentName: hdd/k8s/iscsi/s
          # "" (inherit), lz4, gzip-9, etc
          zvolCompression:
          # "" (inherit), on, off, verify
          zvolDedup:
          zvolEnableReservation: false
          # 512, 1K, 2K, 4K, 8K, 16K, 64K, 128K default is 16K
          zvolBlocksize:

        iscsi:
          targetPortal: "192.168.1.246:3260"
          # for multipath
          targetPortals: [] # [ "server[:port]", "server[:port]", ... ]
          # leave empty to omit usage of -I with iscsiadm
          interface:

          # MUST ensure uniqueness
          # full iqn limit is 223 bytes, plan accordingly
          # default is "{{ name }}"
          #nameTemplate: "{{ parameters.[csi.storage.k8s.io/pvc/namespace] }}-{{ parameters.[csi.storage.k8s.io/pvc/name] }}"
          namePrefix: csi-
          nameSuffix: "-clustera"

          # add as many as needed
          targetGroups:
            # get the correct ID from the "portal" section in the UI
            # https://github.com/democratic-csi/democratic-csi/issues/302
            # NOTE: the ID in the UI does NOT always match the ID in the DB, you must use the DB value
            - targetGroupPortalGroup: 1
              # get the correct ID from the "initiators" section in the UI
              targetGroupInitiatorGroup: 1
              # None, CHAP, or CHAP Mutual
              targetGroupAuthType: None
              # get the correct ID from the "Authorized Access" section of the UI
              # only required if using Chap
              targetGroupAuthGroup:

          #extentCommentTemplate: "{{ parameters.[csi.storage.k8s.io/pvc/namespace] }}/{{ parameters.[csi.storage.k8s.io/pvc/name] }}"
          extentInsecureTpc: true
          extentXenCompat: false
          extentDisablePhysicalBlocksize: true
          # 512, 1024, 2048, or 4096,
          extentBlocksize: 512
          # "" (let FreeNAS decide, currently defaults to SSD), Unknown, SSD, 5400, 7200, 10000, 15000
          extentRpm: "7200"
          # 0-100 (0 == ignore)
          extentAvailThreshold: 0
