apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:qAPrXmoXPhNalKzmX0p+rG2W4u94tp/poDRgYXmQ3Tjxs8xq,iv:XNYxiGocZWyCcT5oGW5KdcDnPZr4jS9nxYGtTod8vvw=,tag:Q/tuHdXQxaPXNjWi/kNrkg==,type:str]
    credentials.json: ENC[AES256_GCM,data:3O0PVrLvPmP8qBRRabwaRs1RB3WoeNvuEfOWxQ9Jigk8nwxKswnooQlhUJIBrb0hdn/mrphSDiy+Lkb/zg4Dcp0R9K7gthJmpFD4hQz6uDqRk9IarLgppgxmBdpJgACerQNA67bhZ/MSIs7b/fQ3XZHBRWLo7h6OKA436c9SKJ1OUuytXQQIITPUX9n7T5e/A0+7PfG8lVi+5AdBMEiROi38ay83vsYI1gFDEsP7oQ==,iv:eyk95MpFSF+FqqbX4dv1IT/L1andKWlHCVmgSf4OdK0=,tag:Mu2KjQAmyyKkTajbK4G3dA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1zeq3kcyj7lyauk0aj6ghqkf9rdcmynlt9mlu3ltq4rkyrka7wpvq3m67zz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxNldvRktVcVlmdEdUSFd5
            ZGhEaVBVbzJsOExudWRDUllZbkhpZmV4dGxvCkJCeU5zVkdBN2xXTy9CVDdhVlEy
            dmJhbEtQUUJpZ0E3QmhkeFVuT3JJS2sKLS0tIFlDTUpqVzlIUXpWdFFsWktJNWg0
            MFljNTF2VW13S1MxS3I5cmJEcjBJS2cKSmOVFd5TvXuq1x+/OU/K4gNZCc0tjg4h
            Oj4f/k4ED6i2N2KKkZU9S1i0ZC/Kmq/ntdqcQbYBKekZSi4kEyb8/A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-09-05T04:41:18Z"
    mac: ENC[AES256_GCM,data:mRFbBexd0r+DNAMQrirUqSN1ZX6XoDJQaV/PnQ+pHukPBcPdK0CSUGMTscRoESwr/aikUYJHpUTuF86eiixThuej/KY0Gv+jJse2CMbb59YtBvsa7FX23xaKBRKEG627kQO0yhzjGPbvaoZjljx6kkQSYWUTZZDyyf6QZhvRor0=,iv:Y9SDmlPstiS9l0/FLzadXkoxJrHOup98hA1rDw7lnb0=,tag:q+fzwjSuzurZ1vtByx0JLQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
