---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: metallb
spec:
  interval: 30m
  chart:
    spec:
      chart: metallb
      version: v1.68.1
      sourceRef:
        kind: HelmRepository
        name: metallb
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    loadBalancerClass: "MetalLB"
