---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: firefly-iii
spec:
  interval: 30m
  chart:
    spec:
      chart: firefly-iii-stack
      version: 0.7.3
      sourceRef:
        kind: HelmRepository
        name: firefly-iii
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    firefly-db:
      storage:
        accessModes: ReadWriteOnce
        dataSize: 2Gi
    firefly-iii:
      config:
        secrets:
          env:
            appKey:
              valueFrom:
                secretKeyRef:
                  name: firefly-secret
                  key: APP_KEY
