---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: pihole
spec:
  interval: 30m
  chart:
    spec:
      chart: pihole
      version: 2.24.0
      sourceRef:
        kind: HelmRepository
        name: mojo2600
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    image:
      tag: 2024.06.0

    dnsmasq:
      customDnsEntries:
        - address=/truenas/192.168.1.246

    persistentVolumeClaim:
      enabled: true
      storageClass: freenas-nfs-csi

    serviceDns:
      mixedService: true
      type: LoadBalancer

    serviceDhcp:
      enabled: false

    ingress:
      enabled: true
      ingressClassName: tailscale
      hosts:
        - pihole
      tls:
        - hosts:
            - pihole

    adminPassword: ${PIHOLE_PASSWORD}

    DNS1: ${UNBOUND_CLUSTER_IP}#5053
    DNS2: null

    extraEnvVars:
      DNSMASQ_LISTENING: all

    adlists:
      - https://raw.githubusercontent.com/PolishFiltersTeam/KADhosts/master/KADhosts.txt
      - https://raw.githubusercontent.com/FadeMind/hosts.extras/master/add.Spam/hosts
      - https://v.firebog.net/hosts/static/w3kbl.txt
      - https://raw.githubusercontent.com/matomo-org/referrer-spam-blacklist/master/spammers.txt
      - https://someonewhocares.org/hosts/zero/hosts
      - https://raw.githubusercontent.com/VeleSila/yhosts/master/hosts
      - https://winhelp2002.mvps.org/hosts.txt
      - https://v.firebog.net/hosts/neohostsbasic.txt
      - https://raw.githubusercontent.com/RooneyMcNibNug/pihole-stuff/master/SNAFU.txt
      - https://paulgb.github.io/BarbBlock/blacklists/hosts-file.txt
      - https://adaway.org/hosts.txt
      - https://v.firebog.net/hosts/AdguardDNS.txt
      - https://v.firebog.net/hosts/Admiral.txt
      - https://raw.githubusercontent.com/anudeepND/blacklist/master/adservers.txt
      - https://v.firebog.net/hosts/Easylist.txt
      - https://pgl.yoyo.org/adservers/serverlist.php?hostformat=hosts&showintro=0&mimetype=plaintext
      - https://raw.githubusercontent.com/FadeMind/hosts.extras/master/UncheckyAds/hosts
      - https://raw.githubusercontent.com/bigdargon/hostsVN/master/hosts
      - https://raw.githubusercontent.com/jdlingyu/ad-wars/master/hosts
      - https://v.firebog.net/hosts/Easyprivacy.txt
      - https://v.firebog.net/hosts/Prigent-Ads.txt
      - https://raw.githubusercontent.com/FadeMind/hosts.extras/master/add.2o7Net/hosts
      - https://raw.githubusercontent.com/crazy-max/WindowsSpyBlocker/master/data/hosts/spy.txt
      - https://hostfiles.frogeye.fr/firstparty-trackers-hosts.txt
      - https://www.github.developerdan.com/hosts/lists/ads-and-tracking-extended.txt
      - https://raw.githubusercontent.com/Perflyst/PiHoleBlocklist/master/android-tracking.txt
      - https://raw.githubusercontent.com/Perflyst/PiHoleBlocklist/master/SmartTV.txt
      - https://raw.githubusercontent.com/Perflyst/PiHoleBlocklist/master/AmazonFireTV.txt
      - https://gitlab.com/quidsup/notrack-blocklists/raw/master/notrack-blocklist.txt
      - https://raw.githubusercontent.com/DandelionSprout/adfilt/master/Alternate%20versions%20Anti-Malware%20List/AntiMalwareHosts.txt
      - https://osint.digitalside.it/Threat-Intel/lists/latestdomains.txt
      - https://v.firebog.net/hosts/Prigent-Crypto.txt
      - https://raw.githubusercontent.com/FadeMind/hosts.extras/master/add.Risk/hosts
      - https://bitbucket.org/ethanr/dns-blacklists/raw/8575c9f96e5b4a1308f2f12394abd86d0927a4a0/bad_lists/Mandiant_APT1_Report_Appendix_D.txt
      - https://phishing.army/download/phishing_army_blocklist_extended.txt
      - https://gitlab.com/quidsup/notrack-blocklists/raw/master/notrack-malware.txt
      - https://v.firebog.net/hosts/RPiList-Malware.txt
      - https://v.firebog.net/hosts/RPiList-Phishing.txt
      - https://raw.githubusercontent.com/Spam404/lists/master/main-blacklist.txt
      - https://raw.githubusercontent.com/AssoEchap/stalkerware-indicators/master/generated/hosts
      - https://urlhaus.abuse.ch/downloads/hostfile/
      - https://malware-filter.gitlab.io/malware-filter/phishing-filter-hosts.txt
      - https://v.firebog.net/hosts/Prigent-Malware.txt
      - https://zerodot1.gitlab.io/CoinBlockerLists/hosts_browser

    whitelist:
      - 0.client-channel.google.com
      - 1drv.com
      - 2.android.pool.ntp.org
      - aa.online-metrix.net
      - ads-field-1a2039d9.aylanetworks.com
      - akamaihd.net
      - akamaitechnologies.com
      - akamaized.net
      - amazonaws.com
      - android.clients.google.com
      - api.applicationinsights.io
      - api.directory.signal.org
      - api.ipify.org
      - api.leanplum.com
      - api.rlje.net
      - app-api.ted.com
      - app-measurement.com
      - appleid.apple.com
      - apps.skype.com
      - appsbackup-pa.clients6.google.com
      - appsbackup-pa.googleapis.com
      - appspot-preview.l.google.com
      - apt.sonarr.tv
      - aspnetcdn.com
      - attestation.xboxlive.com
      - auth.split.io
      - ax.phobos.apple.com.edgesuite.net
      - bit.ly
      - brightcove.net
      - c.s-microsoft.com
      - captive.apple.com
      - cdn.cloudflare.net
      - cdn.embedly.com
      - cdn.optimizely.com
      - cdn.segment.com
      - cdn.signal.org
      - cdn.vidible.tv
      - cdn2.optimizely.com
      - cdn3.optimizely.com
      - cdnjs.cloudflare.com
      - cert.mgt.xboxlive.com
      - chat.signal.org
      - clientconfig.passport.net
      - clients1.google.com
      - clients2.google.com
      - clients3.google.com
      - clients4.google.com
      - clients5.google.com
      - clients6.google.com
      - cms.souqcdn.com
      - config.emb-api.com
      - config2.mparticle.com
      - connectivitycheck.android.com
      - connectivitycheck.gstatic.com
      - contentproxy.signal.org
      - continuum.dds.microsoft.com
      - cpms.spop10.ams.plex.bz
      - cpms35.spop10.ams.plex.bz
      - cse.google.com
      - ctldl.windowsupdate.com
      - cws.conviva.com
      - d2c8v52ll5s99u.cloudfront.net
      - d2gatte9o95jao.cloudfront.net
      - d83eunklitikj.cloudfront.net
      - dashboard.plex.tv
      - data.emb-api.com
      - dataplicity.com
      - dc.services.visualstudio.com
      - def-vef.xboxlive.com
      - delivery.vidible.tv
      - dev.virtualearth.net
      - device.auth.xboxlive.com
      - display.ugc.bazaarvoice.com
      - displaycatalog.mp.microsoft.com
      - dl.delivery.mp.microsoft.com
      - dl.dropbox.com
      - dl.dropboxusercontent.com
      - dns.msftncsi.com
      - download.sonarr.tv
      - drift.com
      - driftt.com
      - dynupdate.no-ip.com
      - ecn.dev.virtualearth.net
      - edge.api.brightcove.com
      - eds.xboxlive.com
      - email.mail.selfh.st
      - fls-na.amazon.com
      - fonts.gstatic.com
      - forums.sonarr.tv
      - g.live.com
      - geo-prod.do.dsp.mp.microsoft.com
      - geo.ngtv.io
      - geo3.ggpht.com
      - gfwsl.geforce.com
      - giphy-proxy-production.whispersystems.org
      - giphy.com
      - github.com
      - github.io
      - global.in.ai.monitor.azure.com
      - googleapis.com
      - gravatar.com
      - gsp-ssl.ls-apple.com.akadns.net
      - gsp-ssl.ls.apple.com
      - gsp1.apple.com
      - gstatic.com
      - gstaticadssl.l.google.com
      - help.ui.xboxlive.com
      - hls.ted.com
      - hulu.com
      - i.s-microsoft.com
      - i.ytimg.com
      - i1.ytimg.com
      - imagesak.secureserver.net
      - img.vidible.tv
      - imgix.net
      - imgs.xkcd.com
      - instantmessaging-pa.googleapis.com
      - intercom.io
      - is1-ssl.mzstatic.com
      - itunes.apple.com
      - jquery.com
      - jsdelivr.net
      - keystone.mwbsys.com
      - lastfm-img2.akamaized.net
      - licensing.xboxlive.com
      - link.leafly.com
      - link.lovevery.com
      - links.notification.intuit.com
      - live.com
      - livepassdl.conviva.com
      - lnk.soccermommyband.com
      - login.live.com
      - login.microsoftonline.com
      - main.iam.ad.ext.azure.com
      - mandrillapp.com
      - manifest.googlevideo.com
      - media.sailthru.com
      - meta-db-worker02.pop.ric.plex.bz
      - meta.plex.bz
      - meta.plex.tv
      - microsoftonline.com
      - msftncsi.com
      - my.plexapp.com
      - new.reddit.com
      - nexusrules.officeapps.live.com
      - nine.plugins.plexapp.com
      - no-ip.com
      - node.plexapp.com
      - notify.xboxlive.com
      - npr-news.streaming.adswizz.com
      - ns1.dropbox.com
      - ns2.dropbox.com
      - nyt.et.e.sparkpost.com
      - o1.email.plex.tv
      - o2.sg0.plex.tv
      - oauthaccountmanager.googleapis.com
      - ocsp.apple.com
      - office.com
      - office.net
      - office365.com
      - officeclient.microsoft.com
      - old.reddit.com
      - om.cbsi.com
      - onedrive.live.com
      - open-telemetry.github.io
      - outlook.live.com
      - outlook.office365.com
      - ow.ly
      - p.typekit.net
      - pihole -w ud-chat.signal.org
      - pings.conviva.com
      - placehold.it
      - placeholdit.imgix.net
      - players.brightcove.net
      - portal.azure.com
      - pricelist.skype.com
      - products.office.com
      - proxy.plex.bz
      - proxy.plex.tv
      - proxy02.pop.ord.plex.bz
      - pubsub.plex.bz
      - pubsub.plex.tv
      - raw.githubusercontent.com
      - reddit-uploaded-media.s3-accelerate.amazonaws.com
      - reddit.map.fastly.net
      - redirector.googlevideo.com
      - res.cloudinary.com
      - s.gateway.messenger.live.com
      - s.marketwatch.com
      - s.mzstatic.com
      - s.shopify.com
      - s.youtube.com
      - s.ytimg.com
      - s1.wp.com
      - s2.youtube.com
      - s3.amazonaws.com
      - sa.symcb.com
      - sdk.split.io
      - secure.avangate.com
      - secure.brightcove.com
      - secure.surveymonkey.com
      - services.chipotle.com
      - services.sonarr.tv
      - shopify.com
      - signal.org
      - skyhook.sonarr.tv
      - souqcdn.com
      - spclient.wg.spotify.com
      - ss3-sleep-1a2039d9-device.aylanetworks.com
      - ssl.p.jwpcdn.com
      - staging.plex.tv
      - status.plex.tv
      - storage.signal.org
      - styles.redditmedia.com
      - support.iam.ad.azure.com
      - t.co
      - t.ly
      - t0.ssl.ak.dynamic.tiles.virtualearth.net
      - t0.ssl.ak.tiles.virtualearth.net
      - tawk.to
      - tedcdn.com
      - textsecure-service-whispersystems.org
      - themoviedb.com
      - thetvdb.com
      - ticketmaster.evyy.net
      - tinyurl.com
      - title.auth.xboxlive.com
      - title.mgt.xboxlive.com
      - tp.47cf2c8c9-frontier.amazon.com
      - tracking-protection.cdn.mozilla.net
      - traffic.libsyn.com
      - transfer.sh
      - turn1.whispersystems.org
      - tvdb2.plex.tv
      - tvthemes.plexapp.com
      - twimg.com
      - ui.skype.com
      - unagi-na.amazon.com
      - unagi.amazon.com
      - updates2.signal.org
      - video-stats.l.google.com
      - videos.vidible.tv
      - vidtech.cbsinteractive.com
      - whispersystems-textsecure-attachments.s3-accelerate.amazonaws.com
      - widget-cdn.rpxnow.com
      - win10.ipv6.microsoft.com
      - wp.com
      - ws.audioscrobbler.com
      - www.amazon.com
      - www.apple.com
      - www.appleiphonecell.com
      - www.bit.ly
      - www.dataplicity.com
      - www.googleapis.com
      - www.msftconnecttest.com
      - www.msftncsi.com
      - www.no-ip.com
      - www.ojrq.net
      - www.reddit.com
      - www.redditmedia.com
      - www.redditstatic.com
      - www.shopify.com
      - www.signal.org
      - www.youtube-nocookie.com
      - xbox.ipv6.microsoft.com
      - xboxexperiencesprod.experimentation.xboxlive.com
      - xflight.xboxlive.com
      - xkms.xboxlive.com
      - xsts.auth.xboxlive.com
      - youtu.be
      - youtube-nocookie.com
      - youtubei.googleapis.com
      - yt3.ggpht.com
      - zee.cws.conviva.com
      - hosts-file.net
      - raw.githubusercontent.com
      - v.firebog.net
      - hostsfile.org
      - someonewhocares.org
      - hostsfile.mine.nu
      - winhelp2002.mvps.org
      - sysctl.org
      - pgl.yoyo.org
      - zeustracker.abuse.ch

    blacklist:
      - cdn.jwplayer.com

    regex:
      - (\.|^)jwplatform\.com$
      - (ads|captive|cloudservices|logs|sr|cs|web|api)\.roku(.admeasurement)*\.com$
      - ^(.+[_.-])?adse?rv(er?|ice)?s?[0-9]*[_.-]
      - ^(.+[_.-])?telemetry[_.-]
      - ^ad([sxv]?[0-9]*|system)[_.-]([^.[:space:]]+\.){1,}|[_.-]ad([sxv]?[0-9]*|system)[_.-]
      - ^adim(age|g)s?[0-9]*[_.-]
      - ^adtrack(er|ing)?[0-9]*[_.-]
      - ^advert(s|is(ing|ements?))?[0-9]*[_.-]
      - ^aff(iliat(es?|ion))?[_.-]
      - ^analytics?[_.-]
      - ^banners?[_.-]
      - ^beacons?[0-9]*[_.-]
      - ^count(ers?)?[0-9]*[_.-]
      - ^mads\.
      - ^pixels?[-.]
      - ^stat(s|istics)?[0-9]*[_.-]

  postRenderers:
    - kustomize:
        patches:
          - target:
              kind: Service
              name: pihole-dns
            patch: |
              - op: add
                path: /spec/loadBalancerClass
                value: tailscale
