---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: homebridge
spec:
  interval: 30m
  chart:
    spec:
      chart: homebridge
      version: 9.1.5
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    image:
      tag: 2024-09-03
    persistence:
      size: 2Gi
