---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    meta.helm.sh/release-name: homebridge
    meta.helm.sh/release-namespace: homebridge
  labels:
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: homebridge
    app.kubernetes.io/part-of: homebridge
    helm.toolkit.fluxcd.io/name: homebridge
    helm.toolkit.fluxcd.io/namespace: homebridge
    k8s-app: homebridge
  name: homebridge
  namespace: homebridge
spec:
  ingressClassName: internal
  rules:
    - host: homebridge.clyde.tech
      http:
        paths:
          - backend:
              service:
                name: homebridge
                port:
                  name: http
            path: /
            pathType: Prefix
