---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: stackgres
spec:
  interval: 30m
  chart:
    spec:
      chart: stackgres-operator
      version: 1.13.0
      sourceRef:
        kind: HelmRepository
        name: stackgres-charts
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    authentication:
      user: admin
