---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tailscale-operator
spec:
  interval: 30m
  chart:
    spec:
      chart: tailscale-operator
      version: v1.66.4
      sourceRef:
        kind: HelmRepository
        name: tailscale
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    oauth:
      clientId: ${TAILSCALE_OAUTH_CLIENT_ID}
      clientSecret: ${TAILSCALE_OAUTH_CLIENT_SECRET}
