---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app unbound
  namespace: flux-system
spec:
  targetNamespace: dns
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  path: ./kubernetes/apps/dns/unbound/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
  patches:
    - patch: |-
        apiVersion: v1
        kind: Service
        metadata:
          name: unbound-dns
          namespace: dns
        spec:
          loadBalancerClass: MetalLB
          loadBalancerIP: 192.168.1.4
      target:
        kind: Service
        name: unbound-dns
        namespace: dns
