---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: unbound
spec:
  interval: 30m
  chart:
    spec:
      chart: unbound
      version: 1.0.3
      sourceRef:
        kind: HelmRepository
        name: pascaliske
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    service:
      dns:
        type: LoadBalancer
    env:
      # -- Timezone for the container.
      - name: TZ
        value: America/Los_Angeles
  postRenderers:
    - kustomize:
        patches:
          - target:
              group: ""
              version: v1
              kind: Service
              name: unbound-dns
              namespace: dns
              labelSelector: "app.kubernetes.io/name=unbound"
            patch: |-
              apiVersion: v1
              kind: Service
              metadata:
                name: unbound-dns
              spec:
                loadBalancerClass: MetalLB
                loadBalancerIP: 192.168.1.4
