---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: unbound
spec:
  interval: 30m
  chart:
    spec:
      chart: unbound
      version: 1.0.3
      sourceRef:
        kind: HelmRepository
        name: pascaliske
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    env:
      # -- Timezone for the container.
      - name: TZ
        value: America/Los_Angeles
